### PR TITLE
September 2021 updates

### PR DESCRIPTION
**Pull request by joelhulen**

### CODE REVIEW

**Review by Rodrigossz — COMMENTED** [review]
Customers can avoid to paste Cosmos DB key for every Synapse Link SQL serverless command. They can use a credential... Can we update this? Specially because of the last security issue, it's good to make everyone confortable.

CREATE CREDENTIAL [credential-name]
    WITH IDENTITY = 'SHARED ACCESS SIGNATURE', SECRET = ''cosmos-db-key"
    
    After that, the queries can use it:
    
    SELECT TOP 100 *
FROM OPENROWSET(​PROVIDER = 'CosmosDB',
                CONNECTION = 'Account=database-account-name;Database=database-name',
                OBJECT = 'container-name,
                SERVER_CREDENTIAL = 'credential-name'
) AS C

**Comment by joelhulen** [comment]
> Customers can avoid to paste Cosmos DB key for every Synapse Link SQL serverless command. They can use a credential... Can we update this? Specially because of the last security issue, it's good to make everyone confortable.
> 
> CREATE CREDENTIAL [credential-name]
> WITH IDENTITY = 'SHARED ACCESS SIGNATURE', SECRET = ''cosmos-db-key"
> 
> ```
> After that, the queries can use it:
> 
> SELECT TOP 100 *
> ```
> 
> FROM OPENROWSET(​PROVIDER = 'CosmosDB',
> CONNECTION = 'Account=database-account-name;Database=database-name',
> OBJECT = 'container-name,
> SERVER_CREDENTIAL = 'credential-name'
> ) AS C

@Rodrigossz this is a great idea. I'll make that change today. Thanks :)

**Comment by joelhulen** [comment]
@Rodrigossz I've updated the Synapse serverless SQL scripts to use a server credential instead.

**Comment by Rodrigossz** [comment]
> @Rodrigossz I've updated the Synapse serverless SQL scripts to use a server credential instead.

Excellent!!

**Review by Rodrigossz — APPROVED** [review]

**Review by sesmyrnov — COMMENTED** [review]
Content looks great, but I have 3 suggestions to enhance it (I'm not sure this can be in scope for this release so I'm just making a generic comments here):
1) Excersize8: Task3 (PBI report): add a section/step to configure a data refresh (since we select inport data) and validate data refresh in Report after publishing while data load is running to show the replication value end-to-end. 

2)  We illustrate in Excersize6:Task2 how to query nested JSON using CROSSAPPLY, but we also should have an exmaple how to query JSON ARRAY object as well as this is very common with Cosmos JSON doc structures where we effectivley use embedding for 1:few relationships. You can potentially expand this use-case by converting "phone"/"email" attributes to an array of emails/phones with some other "type" property to differentiate (like home, mobile or default/other) and illustrate how to explode the array in the SQL Serverless query/SPARK as this is common ask.

3) THe lab showcase Cosmos SQL API - but we also need to have a similar example/lab for Cosmos Mongo API for similar worklolad. I would love to see the same lab ported to also load into Cosmos Mongo API and have a version of Synapse queries/Views/Spark notebooks for that where they will be different.

**Comment by joelhulen** [comment]
@sesmyrnov thank you for your feedback. I have updated the lab to address your first point, which is to add Power BI report refresh instructions. As for your second point, it will take some time to implement that change. This feedback should have been provided before the update work began. Given that we are at the end of the review period, I think we should make note of that suggestion and plan on adding nested JSON queries in the next update.

As for your last point, that is a great suggestion, but it is outside of the scope of this update. I will have to defer to the MCW stakeholders as to whether they wish to invest in a Mongo version in a future update.

@DawnmarieDesJardins - I have addressed all of the feedback that I can for this update. Please do a QC check and prepare for merging my updates.

Thank you!

**Comment by sesmyrnov** [comment]
@Joelhulen - thanks for aknowledging those points. Regaridng PBI refresh update - I see that you added a steps to refresh PBI desktop report to show diff, but I was more suggesting to push that refresh to a PBI workspace dataset refreshing after it is published based on this to illustrate options for one-time refresh or scheduled interval refresh based on this: https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data# 

agree on the other points that it is probably too late to add them now - but would be good to consider for future phase 2 updates to this repo.

**Pull request merged**
